### ISSUE TITLE
Missing Validation in DTOs and Incomplete Route in Controller

### ISSUE THREAD

**Issue by mesalm** [NestJS-framework/nest-demo#1]
Hello! I noticed a couple of improvements that could enhance the structure and reliability of the project:

DTO Validation: The DTO currently lacks validation for required fields, such as ensuring that certain fields are required and are of type string. Adding this validation would help prevent errors and improve data consistency.
Controller Route Issue: In the controller, there's a route (findOne) that doesn't seem to be implemented in the service. Adding this missing method in the service would help complete the functionality of the route.

Would you be open to these changes? If so, I'm happy to implement them myself. Could you also add the hacktoberfest-accepted label to this issue?

Thanks for considering!

**Comment by sunny7899** [comment]
Go ahead @mesalm
